# Generated by Django 5.2.3 on 2025-06-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dynamicformsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicformsubmission',
            name='form_name',
        ),
    ]
